import Link from "next/link";
import { redirect } from "next/navigation";
import { createEvent } from "./actions";
import { requireUser } from "@/lib/auth";
import { createClient } from "@/lib/supabase/server";
export default async function Onboarding({searchParams}:{searchParams:Promise<{message?:string}>}){
  const user=await requireUser();const supabase=await createClient();
  const {data:existing}=await supabase.from("events").select("id").eq("owner_id",user.id).maybeSingle();if(existing)redirect("/dashboard");
  const {message}=await searchParams;
  return <div className="onboard-page"><header className="app-header"><Link className="brand" href="/"><span>ev.</span> EverAfter</Link><span className="muted">Create your event · One account, one page</span><Link href="/">Exit setup</Link></header><main className="onboard-wrap"><div className="progress"><i/><i/><i/><i/></div><p className="eyebrow">Let&apos;s begin</p><h1>What are we gathering for?</h1><p className="onboard-lead">Choose your occasion and the system will prepare every section you need. You can personalize them from your dashboard.</p>{message&&<div className="auth-message">{message}</div>}<form action={createEvent}><div className="type-grid"><label className="type-card"><input className="type-radio" type="radio" name="eventType" value="wedding" defaultChecked/><span className="type-art wedding-mini">A <i>&amp;</i> K</span><b>Wedding</b><small>Joyful, warm and celebratory</small></label><label className="type-card"><input className="type-radio" type="radio" name="eventType" value="memorial"/><span className="type-art memorial-mini">KM</span><b>Funeral or memorial</b><small>Calm, dignified and reflective</small></label></div><div className="form-preview panel onboarding-fields"><label>Event page title<input name="title" placeholder="Ama & Kojo or Remembering Kofi Mensah" required minLength={3}/></label><label>Event date<input name="eventDate" type="date"/></label><label>Your preferred page address<div className="slug-field"><span>everafter.com/</span><input name="slug" placeholder="ama-and-kojo" required pattern="[a-z0-9]+(?:-[a-z0-9]+)*"/><b>Unique</b></div></label><small>Use lowercase letters, numbers and hyphens. Availability is confirmed when you continue.</small></div><div className="onboard-actions"><Link href="/" className="text-link">Back</Link><button className="button button-coral" type="submit">Create my event workspace →</button></div></form></main></div>;
}
