import type {SupabaseClient} from "@supabase/supabase-js";
import {DashboardNav} from "@/components/dashboard-nav";
import {getOwnerEvent} from "@/lib/event-owner";
import {createClient} from "@/lib/supabase/server";
import {beginCheckout,requestCustomDomain,verifyCustomDomain} from "./actions";
import "./billing.css";

export default async function BillingPage({searchParams}:{searchParams:Promise<{message?:string;payment?:string}>}){
  const{event,user}=await getOwnerEvent();const query=await searchParams;const supabase=await createClient();const db=supabase as unknown as SupabaseClient;
  const[{data:plans},{data:addons},{data:orders},{data:domain}]=await Promise.all([db.from("event_plans").select("*").eq("active",true).order("price_ghs"),db.from("storage_addons").select("*").eq("active",true).order("price_ghs"),db.from("payment_orders").select("*").eq("owner_id",user.id).order("created_at",{ascending:false}).limit(8),db.from("custom_domains").select("*").eq("event_id",event.id).maybeSingle()]);
  const paymentsReady=process.env.PAYMENTS_ENABLED==="true"&&Boolean(process.env.PAYSTACK_SECRET_KEY)&&Boolean(process.env.FLUTTERWAVE_SECRET_KEY);const cname=process.env.CUSTOM_DOMAIN_CNAME??"cname.vercel-dns.com";
  return <div className="app-shell"><DashboardNav active="Plan"/><main className="app-main billing-page">
    <div className="page-heading"><div><p className="eyebrow">V3 plans & growth</p><h1>Plan, storage and domain</h1><p>One-time purchases only—no recurring subscription and no surprise renewal.</p></div><span className="plan-badge">{event.plan_code} plan</span></div>
    {(query.message||query.payment)&&<div className={query.payment==="success"?"rsvp-success":"auth-message"}>{query.payment==="success"?"Payment verified. Your entitlement is now active.":query.payment==="failed"?"Payment was not completed or could not be verified.":query.message}</div>}
    {!paymentsReady&&<div className="billing-notice"><b>Checkout safety lock is on</b><span>The commercial experience is complete, but charges remain disabled until the production merchant secrets are configured.</span></div>}
    <section className="billing-section"><div className="billing-heading"><p className="eyebrow">One event · one payment</p><h2>Choose the publishing level</h2></div><div className="plan-grid">{(plans??[]).map(plan=><article className={`plan-card${plan.code===event.plan_code?" current":""}`} key={plan.code}><span>{plan.code===event.plan_code?"Current plan":plan.code==="premium"?"Best for planners":"Essential publishing"}</span><h3>{plan.name}</h3><div className="price-switch"><b>GH₵ {Number(plan.price_ghs).toFixed(0)}</b><small>or US$ {Number(plan.price_usd).toFixed(0)}</small></div><ul><li>{Math.round(Number(plan.storage_bytes)/1073741824)} GB media storage</li><li>{plan.template_limit??"Unlimited"} curated templates</li><li>{plan.branding_removed?"Platform branding removed":"EverAfter footer branding"}</li><li>{plan.custom_domain_enabled?"Custom domain included":"Simple EverAfter event link"}</li></ul>{plan.code!==event.plan_code&&<div className="checkout-row"><form action={beginCheckout}><input type="hidden" name="purpose" value="event_plan"/><input type="hidden" name="product" value={plan.code}/><button name="currency" value="GHS">Pay GHS · Card/MoMo</button></form><form action={beginCheckout}><input type="hidden" name="purpose" value="event_plan"/><input type="hidden" name="product" value={plan.code}/><button className="secondary" name="currency" value="USD">Pay USD · Card</button></form></div>}</article>)}</div></section>
    <section className="billing-section storage-section"><div><p className="eyebrow">Flexible gallery space</p><h2>Add storage without changing plan</h2><p>{(event.storage_used_bytes/1073741824).toFixed(2)} GB of {(event.storage_limit_bytes/1073741824).toFixed(0)} GB used</p><div className="storage-meter"><i style={{width:`${Math.min(100,event.storage_used_bytes/event.storage_limit_bytes*100)}%`}}/></div></div><div className="addon-grid">{(addons??[]).map(addon=><article key={addon.code}><span>+</span><h3>{addon.name}</h3><p>GH₵ {Number(addon.price_ghs).toFixed(0)} · US$ {Number(addon.price_usd).toFixed(0)}</p><div className="checkout-row compact"><form action={beginCheckout}><input type="hidden" name="purpose" value="storage_addon"/><input type="hidden" name="product" value={addon.code}/><button name="currency" value="GHS">GHS</button></form><form action={beginCheckout}><input type="hidden" name="purpose" value="storage_addon"/><input type="hidden" name="product" value={addon.code}/><button className="secondary" name="currency" value="USD">USD</button></form></div></article>)}</div></section>
    <section className={`billing-section domain-section${event.plan_code!=="premium"?" locked":""}`}><div><p className="eyebrow">Premium custom domain</p><h2>Publish on your own address</h2><p>Use a domain such as <b>amaandkojo.com</b> while keeping the same editor, guest list and gallery.</p></div>{event.plan_code==="premium"?<div className="domain-card"><form action={requestCustomDomain}><label>Domain you own<input name="hostname" placeholder="ourcelebration.com" defaultValue={domain?.hostname??""} required/></label><button className="button button-dark">Save domain</button></form>{domain&&<div className="dns-records"><span className={`domain-status status-${domain.status}`}>{domain.status}</span><p>Add these records with your DNS provider:</p><code>CNAME @ → {cname}</code><code>TXT _everafter → {domain.verification_token}</code><form action={verifyCustomDomain}><button className="button panel-button">Check DNS verification</button></form></div>}</div>:<div className="locked-card"><b>Premium feature</b><p>Upgrade once to unlock custom domains and remove EverAfter branding.</p></div>}</section>
    {orders&&orders.length>0&&<section className="billing-section"><div className="billing-heading"><p className="eyebrow">Receipts & attempts</p><h2>Payment history</h2></div><div className="order-list">{orders.map(order=><article key={order.id}><span>{new Intl.DateTimeFormat("en-GB",{dateStyle:"medium"}).format(new Date(order.created_at))}</span><b>{String(order.purpose).replace("_"," ")}</b><span>{order.currency} {Number(order.amount).toFixed(2)}</span><em className={`order-${order.status}`}>{order.status}</em></article>)}</div></section>}
  </main></div>;
}
