import Link from "next/link";
import { signIn, signInWithGoogle, signUp } from "@/app/auth/actions";

export default async function LoginPage({ searchParams }: { searchParams: Promise<{ mode?: string; message?: string }> }) {
  const params = await searchParams;
  const signup = params.mode === "signup";
  const googleEnabled = process.env.NEXT_PUBLIC_GOOGLE_AUTH_ENABLED === "true";
  return <main className="auth-page"><section className="auth-aside"><Link className="brand" href="/"><span>ev.</span> EverAfter</Link><div><p className="eyebrow">A meaningful home for your event</p><h1>Share every detail.<br/>Keep every memory.</h1><p>Create one secure, beautiful page for your wedding or memorial.</p></div><small>Placeholder brand · V1 authentication</small></section><section className="auth-form-wrap"><div className="auth-form"><p className="eyebrow">{signup ? "Create your account" : "Welcome back"}</p><h2>{signup ? "Begin your event page." : "Sign in to your event."}</h2><p>{signup ? "One account manages one event." : "Manage your details, guests and gallery."}</p>{params.message && <div className="auth-message">{params.message}</div>}{googleEnabled&&<><form action={signInWithGoogle}><button className="google-button" type="submit"><b>G</b> Continue with Google</button></form><div className="divider"><span>or continue with email</span></div></>}<form action={signup ? signUp : signIn} className="auth-fields">{signup && <label>Your name<input name="displayName" autoComplete="name" required minLength={2}/></label>}<label>Email address<input name="email" type="email" autoComplete="email" required/></label><label>Password<input name="password" type="password" autoComplete={signup ? "new-password" : "current-password"} required minLength={8}/></label>{!signup&&<Link className="forgot-link" href="/forgot-password">Forgot your password?</Link>}<button className="button button-coral full" type="submit">{signup ? "Create account" : "Sign in"}</button></form>{!googleEnabled&&<p className="provider-note">Google sign-in will appear after the Google provider is connected.</p>}<p className="auth-switch">{signup ? "Already have an account?" : "New to EverAfter?"} <Link href={signup ? "/login" : "/login?mode=signup"}>{signup ? "Sign in" : "Create an account"}</Link></p><small>By continuing, you agree to our placeholder Terms and Privacy Policy.</small></div></section></main>;
}
