import Link from "next/link";
import {redirect} from "next/navigation";
import {createClient} from "@/lib/supabase/server";

export default async function Admin(){
  const supabase=await createClient();const{data:{user}}=await supabase.auth.getUser();if(!user)redirect("/login");
  const{data:profile}=await supabase.from("profiles").select("is_admin").eq("id",user.id).maybeSingle();if(!profile?.is_admin)redirect("/dashboard");
  const[{data:events},{count:users},{count:rsvps}]=await Promise.all([supabase.from("events").select("id,title,event_type,status,storage_used_bytes,created_at").order("created_at",{ascending:false}).limit(50),supabase.from("profiles").select("id",{count:"exact",head:true}),supabase.from("rsvps").select("id",{count:"exact",head:true})]);
  const storage=(events??[]).reduce((sum,event)=>sum+event.storage_used_bytes,0);
  return <div className="app-shell"><header className="app-header"><Link className="brand" href="/"><span>ev.</span> EverAfter <small>ADMIN</small></Link><nav className="dash-nav"><b>Overview</b><Link href="/dashboard">Owner dashboard</Link></nav></header><main className="app-main"><div className="page-heading"><div><p className="eyebrow">Platform administration</p><h1>Overview</h1><p>Live, permission-scoped platform data.</p></div></div><div className="grid-3 admin-stats"><article className="panel"><span>Accounts</span><strong>{users??0}</strong></article><article className="panel"><span>Events</span><strong>{events?.length??0}</strong><small>{rsvps??0} RSVP records</small></article><article className="panel"><span>Storage</span><strong>{(storage/1073741824).toFixed(1)} GB</strong></article></div><div className="panel table-panel"><div className="panel-title"><div><h3>Recent events</h3><p>Publication state and usage.</p></div></div><div className="data-table"><div className="table-row table-head"><span>Event</span><span>Type</span><span>Status</span><span>Created</span><span>Storage</span><span/></div>{events?.map(event=><div className="table-row" key={event.id}><b>{event.title}</b><span>{event.event_type}</span><span>{event.status}</span><span>{new Intl.DateTimeFormat("en-GB").format(new Date(event.created_at))}</span><span>{(event.storage_used_bytes/1048576).toFixed(1)} MB</span><span/></div>)}</div></div><p className="security-note">Admin reads are enforced by database row-level security.</p></main></div>;
}
