"use server";
import {revalidatePath} from "next/cache";
import {redirect} from "next/navigation";
import {getOwnerEvent} from "@/lib/event-owner";
async function ownerEvent(){return getOwnerEvent()}
export async function updateEvent(form:FormData){const {supabase,event}=await ownerEvent();const status=["draft","published","unpublished"].includes(String(form.get("status")))?String(form.get("status")):"draft";const visibility=["public","protected","private"].includes(String(form.get("visibility")))?String(form.get("visibility")):"private";const title=String(form.get("title")??"").trim().slice(0,120);const excerpt=String(form.get("excerpt")??"").trim().slice(0,500);const eventDate=String(form.get("eventDate")??"")||null;const deadline=String(form.get("rsvpDeadline")??"")||null;const maxParty=Math.min(20,Math.max(1,Number(form.get("maxPartySize"))||1));const requestedTheme=String(form.get("theme"));const theme=["classic","garden","editorial"].includes(requestedTheme)||(event.plan_code==="premium"&&["cinematic","minimalist"].includes(requestedTheme))?requestedTheme:"classic";const color=["rose","sage","champagne","terracotta","plum","midnight"].includes(String(form.get("color")))?String(form.get("color")):"rose";const font=["editorial","modern","romantic"].includes(String(form.get("font")))?String(form.get("font")):"editorial";const published=status==="published";if(!title)redirect("/dashboard/settings?message=Page%20title%20is%20required");const{data,error}=await supabase.from("events").update({title,excerpt,event_date:eventDate,status,visibility,published_at:published?new Date().toISOString():null,rsvp_enabled:form.get("rsvpEnabled")==="on",rsvp_deadline:deadline?new Date(deadline).toISOString():null,max_party_size:maxParty,allow_photo_downloads:form.get("allowDownloads")==="on",theme_key:theme,color_key:color,font_key:font}).eq("id",event.id).select("id").maybeSingle();if(error)redirect(`/dashboard/settings?message=${encodeURIComponent(error.message)}`);if(!data)redirect("/dashboard/settings?message=Settings%20could%20not%20be%20saved");revalidatePath("/dashboard/settings");revalidatePath("/dashboard");revalidatePath(`/${event.slug}`);redirect("/dashboard/settings?message=saved")}
export async function updateSection(form:FormData){const {supabase,event}=await ownerEvent();const id=Number(form.get("id"));if(!Number.isSafeInteger(id)||id<1)return{ok:false,message:"This section could not be identified. Refresh the page and try again."};const heading=String(form.get("heading")??"").trim().slice(0,160);const body=String(form.get("body")??"").trim().slice(0,10000);const{data,error}=await supabase.from("event_sections").update({heading:heading||null,body:{text:body},is_visible:form.get("visible")==="on"}).eq("id",id).eq("event_id",event.id).select("id").maybeSingle();if(error)return{ok:false,message:error.message};if(!data)return{ok:false,message:"The section was not saved. Please refresh and try again."};revalidatePath(`/${event.slug}`);return{ok:true,message:"Section saved."}}
export async function addVenue(form:FormData){const {supabase,event}=await ownerEvent();await supabase.from("venues").insert({event_id:event.id,name:String(form.get("name")),address:String(form.get("address")??""),map_url:String(form.get("mapUrl")??"")||null,directions:String(form.get("directions")??"")||null});revalidatePath("/dashboard/schedule")}
export async function addSchedule(form:FormData){const {supabase,event}=await ownerEvent();await supabase.from("schedule_items").insert({event_id:event.id,title:String(form.get("title")),description:String(form.get("description")??"")||null,starts_at:new Date(String(form.get("startsAt"))).toISOString(),venue_id:Number(form.get("venueId"))||null});revalidatePath("/dashboard/schedule")}
export async function deleteRecord(form:FormData){const {supabase,event}=await ownerEvent();const table=String(form.get("table"));const allowed=["venues","schedule_items","albums","media","documents"] as const;if(!allowed.includes(table as typeof allowed[number]))return;const id=Number(form.get("id"));if(!Number.isSafeInteger(id))return;if(table==="media"||table==="documents"){const {data:file}=await supabase.from(table).select("storage_path").eq("id",id).eq("event_id",event.id).maybeSingle();if(file?.storage_path)await supabase.storage.from("event-media").remove([file.storage_path])}await supabase.from(table as typeof allowed[number]).delete().eq("id",id).eq("event_id",event.id);revalidatePath("/dashboard/schedule");revalidatePath("/dashboard/gallery");revalidatePath(`/${event.slug}`)}
export async function updateRsvp(form:FormData){const {supabase,event}=await ownerEvent();const id=Number(form.get("id"));const action=String(form.get("action"));if(action==="delete")await supabase.from("rsvps").delete().eq("id",id).eq("event_id",event.id);else await supabase.from("rsvps").update({checked_in_at:action==="checkin"?new Date().toISOString():null}).eq("id",id).eq("event_id",event.id);revalidatePath("/dashboard/guests")}
export async function moderateTribute(form:FormData){const {supabase,event}=await ownerEvent();await supabase.from("tributes").update({status:String(form.get("status")),moderated_at:new Date().toISOString()}).eq("id",Number(form.get("id"))).eq("event_id",event.id);revalidatePath("/dashboard/tributes")}
export async function createAlbum(form:FormData){const {supabase,event}=await ownerEvent();await supabase.from("albums").insert({event_id:event.id,title:String(form.get("title")),description:String(form.get("description")??"")||null,allow_downloads:form.get("allowDownloads")==="on"});revalidatePath("/dashboard/gallery")}
export async function setPublicationStatus(form:FormData){const{supabase,event}=await ownerEvent();const publish=String(form.get("publish"))==="true";const{error}=await supabase.from("events").update({status:publish?"published":"draft",published_at:publish?new Date().toISOString():null}).eq("id",event.id);if(error)redirect(`/dashboard/settings?password=${encodeURIComponent(error.message)}`);revalidatePath("/dashboard");revalidatePath(`/${event.slug}`);redirect("/dashboard")}

export async function setEventPassword(form:FormData){const{supabase,event}=await ownerEvent();const password=String(form.get("password")??"");const confirm=String(form.get("confirm")??"");if(password.length<8||password.length>128||password!==confirm)redirect("/dashboard/settings?password=invalid");const{error}=await supabase.rpc("set_event_password",{p_event_id:event.id,p_password:password});if(error)redirect(`/dashboard/settings?password=${encodeURIComponent(error.message)}`);revalidatePath(`/${event.slug}`);redirect("/dashboard/settings?password=saved")}

export async function clearEventPassword(){const{supabase,event}=await ownerEvent();await supabase.rpc("clear_event_password",{p_event_id:event.id});await supabase.from("events").update({visibility:"private"}).eq("id",event.id);revalidatePath(`/${event.slug}`);redirect("/dashboard/settings?password=cleared")}
