import {invitationSettings} from "@/lib/invitation";
import Link from "next/link";
import {DashboardNav} from "@/components/dashboard-nav";
import {CopyLinkButton} from "@/components/copy-link-button";
import {getOwnerEvent} from "@/lib/event-owner";
import {setPublicationStatus} from "./actions";

export default async function Dashboard(){
  const{supabase,event,role,events}=await getOwnerEvent();
  const[{count:rsvpCount},{count:photoCount}]=await Promise.all([supabase.from("rsvps").select("id",{count:"exact",head:true}).eq("event_id",event.id),supabase.from("media").select("id",{count:"exact",head:true}).eq("event_id",event.id)]);
  const coverEnabled=invitationSettings(event.invitation_cover).enabled;const publicHref=`/${event.slug}`;
  return <div className="app-shell"><DashboardNav active="Overview"/><main className="app-main">
    <div className="page-heading"><div><p className="eyebrow">Your event</p><h1>{event.title}</h1><p>{event.event_type==="wedding"?"Wedding":"Memorial"} · {event.event_date??"Date not set"} · {events.length} accessible {events.length===1?"event":"events"}</p></div><div className="button-row"><Link href="/dashboard/events" className="button panel-button">Switch event</Link><Link href={publicHref} className="button panel-button">Preview page ↗</Link>{["owner","planner"].includes(role)&&<form action={setPublicationStatus}><button className="button button-dark" name="publish" value={event.status==="published"?"false":"true"}>{event.status==="published"?"Unpublish":"Publish page"}</button></form>}</div></div>
    <section className="dashboard-welcome"><div><p className="eyebrow">{event.event_type==="wedding"?"A welcome that feels like you":"A space to remember"}</p><h2>{event.event_type==="wedding"?"Start with a lovely invitation.":"Bring the memories together."}</h2><p>{event.event_type==="wedding"?(coverEnabled?"Your invitation cover is on. Preview the welcome or make a few personal touches.":"Add a personal card that opens to reveal your celebration."):"Share a story, gather photographs, and help loved ones find the details."}</p><Link className="button button-dark" href={event.event_type==="wedding"?"/dashboard/settings#invitation":"/dashboard/editor"}>{event.event_type==="wedding"?(coverEnabled?"Edit invitation":"Create your welcome"):"Edit the story"} ↗</Link></div><div className="dashboard-seal" aria-hidden="true">{event.event_type==="wedding"?"With love":"In memory"}<span>✳</span>{event.title}</div></section>
    <div className="stat-grid"><article className="panel stat"><span>RSVP responses</span><strong>{rsvpCount??0}</strong><Link href="/dashboard/guests">Manage guests →</Link></article><article className="panel stat"><span>Page status</span><strong>{event.status}</strong><small>{event.visibility} visibility</small></article><article className="panel stat"><span>Photographs</span><strong>{photoCount??0}</strong><Link href="/dashboard/gallery">Manage gallery →</Link></article></div>
    <div className="grid-2 manage-grid"><section className="panel"><h2>Your event link</h2><div className="copy-link"><span>/{event.slug}</span><CopyLinkButton path={publicHref}/></div><Link className="button button-dark full" href={publicHref}>Preview experience ↗</Link></section><section className="panel action-list"><h3>Make it ready to share</h3><Link href="/dashboard/editor"><b>01</b><span>Tell your story<small>Edit every page section</small></span>→</Link><Link href="/dashboard/schedule"><b>02</b><span>Plan the day<small>Venues and programme</small></span>→</Link><Link href="/dashboard/settings"><b>03</b><span>Choose your look<small>Invitation, appearance and sharing</small></span>→</Link></section></div>
  </main></div>;
}
